#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
import shlex
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlparse


DEFAULT_UNIVERSAL_LINK = "https://api.mewpow.com/xiaonaiping/wechat/"
PLACEHOLDER_MARKERS = (
    "placeholder",
    "example",
    "replace",
    "changeme",
    "todo",
    "debug",
    "dryrun",
    "test",
    "your",
)
SAMPLE_APP_ID_BODIES = {
    "0123456789abcdef",
    "1234567890abcdef",
    "abcdef1234567890",
    "fedcba9876543210",
}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def is_real_wechat_app_id(value: str) -> bool:
    value = value.strip()
    lower = value.lower()
    if any(marker in lower for marker in PLACEHOLDER_MARKERS):
        return False
    if re.fullmatch(r"wx[0-9a-fA-F]{16}", value) is None:
        return False

    body = lower[2:]
    if body in SAMPLE_APP_ID_BODIES:
        return False
    if body == body[0] * len(body):
        return False
    return True


def valid_universal_link(value: str) -> bool:
    parsed = urlparse(value.strip())
    return (
        parsed.scheme == "https"
        and parsed.netloc == "api.mewpow.com"
        and parsed.path.startswith("/xiaonaiping/wechat/")
    )


def export_lines(values: dict[str, str]) -> str:
    lines = [
        "# Generated by Backend/scripts/prepare_wechat_release_env.py",
        "# Contains WeChat client identifiers only. Do not add AppSecret here.",
    ]
    lines.extend(f"export {key}={shlex.quote(value)}" for key, value in values.items())
    return "\n".join(lines) + "\n"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def build_report(args: argparse.Namespace) -> dict[str, Any]:
    started_at = utc_now()
    app_id = args.app_id.strip()
    url_scheme = (args.url_scheme or app_id).strip()
    universal_link = (args.universal_link or DEFAULT_UNIVERSAL_LINK).strip()

    checks: dict[str, dict[str, Any]] = {}

    def add(name: str, passed: bool, evidence: str) -> None:
        checks[name] = {"passed": passed, "required": True, "evidence": evidence}

    add(
        "appIDLooksReal",
        is_real_wechat_app_id(app_id),
        "AppID matches wx + 16 hex and is not placeholder/sample"
        if is_real_wechat_app_id(app_id)
        else "AppID must match wx + 16 hex and must not contain placeholder/sample/debug/test markers",
    )
    add(
        "urlSchemeLooksReal",
        is_real_wechat_app_id(url_scheme),
        "URL Scheme matches wx + 16 hex and is not placeholder/sample"
        if is_real_wechat_app_id(url_scheme)
        else "URL Scheme must match wx + 16 hex and must not contain placeholder/sample/debug/test markers",
    )
    add(
        "urlSchemeMatchesAppID",
        app_id == url_scheme,
        "URL Scheme equals AppID" if app_id == url_scheme else "URL Scheme must equal AppID",
    )
    add(
        "universalLinkAllowed",
        valid_universal_link(universal_link),
        "Universal Link is the xiaonaiping WeChat HTTPS path on api.mewpow.com"
        if valid_universal_link(universal_link)
        else "Universal Link must be https://api.mewpow.com/xiaonaiping/wechat/...",
    )

    failed = [name for name, check in checks.items() if check["passed"] is not True]
    env_values = {
        "XNP_WECHAT_APP_ID": app_id,
        "XNP_WECHAT_URL_SCHEME": url_scheme,
        "XNP_WECHAT_UNIVERSAL_LINK": universal_link,
    }

    return {
        "startedAt": started_at,
        "completedAt": utc_now(),
        "passed": not failed,
        "containsSecrets": False,
        "failedRequiredChecks": failed,
        "envKeys": list(env_values.keys()),
        "checks": checks,
        "envValues": env_values if args.include_values_in_json else {},
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--app-id", required=True)
    parser.add_argument("--url-scheme", default="")
    parser.add_argument("--universal-link", default=DEFAULT_UNIVERSAL_LINK)
    parser.add_argument("--output-env", default="")
    parser.add_argument("--output-json", default="")
    parser.add_argument("--include-values-in-json", action="store_true")
    parser.add_argument("--print-env", action="store_true")
    args = parser.parse_args()

    report = build_report(args)
    env_values = {
        "XNP_WECHAT_APP_ID": args.app_id.strip(),
        "XNP_WECHAT_URL_SCHEME": (args.url_scheme or args.app_id).strip(),
        "XNP_WECHAT_UNIVERSAL_LINK": (args.universal_link or DEFAULT_UNIVERSAL_LINK).strip(),
    }
    env_text = export_lines(env_values)

    if args.output_json:
        output_json = Path(args.output_json)
        if not output_json.is_absolute():
            output_json = repo_root() / output_json
        write_text(output_json, json.dumps(report, ensure_ascii=False, indent=2) + "\n")

    if args.output_env:
        output_env = Path(args.output_env)
        if not output_env.is_absolute():
            output_env = repo_root() / output_env
        if report["passed"]:
            write_text(output_env, env_text)
        else:
            print("refusing to write env file because validation failed", file=sys.stderr)

    if args.print_env and report["passed"]:
        print(env_text, end="")
    elif not report["passed"]:
        print(json.dumps(report, ensure_ascii=False, indent=2), file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
